### ISSUE TITLE
dont need a class for this

### ISSUE THREAD

**Issue by matcool** [29cmb/CleanMenu#1]
https://github.com/29cmb/CleanMenu/blob/265143062507a63b0ed4b2e3f2f8e139179845c5/src/main.cpp#L25

this isnt 2021 modding, you can just put the callback in the same class:
https://docs.geode-sdk.org/tutorials/modify#giving-a-class-name

**Comment by 29cmb** [comment]
Has been changed in development file and will come with v1.2.0 when I get to adding some more features
