### ISSUE TITLE
The menu isn't very clean actually 

### ISSUE THREAD

**Issue by im-blad** [29cmb/CleanMenu#7]
![Screenshot_2024-06-09-12-33-26-241_com geode launcher-edit](https://github.com/29cmb/CleanMenu/assets/148497646/c0c0fd50-c786-4580-9486-c51908ac30f0)

**Comment by 29cmb** [comment]
This is an issue with the progression mod, it causes some buttons to be mis-aligned for whatever reason. I will put an incompatibility soon
